
version: '3.7'

networks:
  noescalapp-app-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
    
services:

  load-balancer:
    image: nginx:alpine
    container_name: nginx-load-balancer
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.2
    ports:
      - "8081:8081"
    volumes:
      - ./nginx:/etc/nginx/

  api-1:
    build: .
    image: no-escala-app-compose
    container_name: no-escala-app-1
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.10
    ports:
      - "8082:8080"
    working_dir: /home/app
    command: mvn spring-boot:run
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  api-2:
    image: no-escala-app-compose
    container_name: no-escala-app-2
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.20
    ports:
      - "8083:8080"
    working_dir: /home/app
    command: mvn spring-boot:run
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  api-3:
    image: no-escala-app-compose
    container_name: no-escala-app-3
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.30
    ports:
      - "8084:8080"
    working_dir: /home/app
    command: mvn spring-boot:run
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
          
  redis-master:
    image: 'redis:latest'
    container_name: redisDB-master
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    working_dir: /redis
    volumes:
      - ./redis-master-config:/redis

  redis-slave-1:
    image: 'redis:latest'
    container_name: redisDB-slave-1
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6380:6380"
    working_dir: /redis
    volumes:
      - ./redis-slave-1-config:/redis
    command: redis-server --port 6380 --replicaof redis-master 6379
    
  redis-slave-2:
    image: 'redis:latest'
    container_name: redisDB-slave-2
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6381:6381"
    working_dir: /redis
    volumes:
      - ./redis-slave-2-config:/redis
    command: redis-server --port 6381 --replicaof redis-master 6379

  sentinel-1:
    image: 'redis:latest'
    container_name: redis-sentinel-1
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26379:26379"
    working_dir: /redis
    volumes:
      - ./redis-sentinel-1-config:/redis
    command: redis-server /redis/sentinel.conf --sentinel

  sentinel-2:
    image: 'redis:latest'
    container_name: redis-sentinel-2
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26380:26380"
    working_dir: /redis
    volumes:
      - ./redis-sentinel-2-config:/redis
    command: redis-server /redis/sentinel.conf --sentinel 

  sentinel-3:
    image: 'redis:latest'
    container_name: redis-sentinel-3
    networks:
      noescalapp-app-tier:
        ipv4_address: 172.20.0.8
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26381:26381"
    working_dir: /redis
    volumes:
      - ./redis-sentinel-3-config:/redis
    command: redis-server /redis/sentinel.conf --sentinel 